### PR TITLE
Add books and notification page 

### PR DESCRIPTION
**Pull request by piyuuussh**
Add books and Notification page is added in the the code.

### CODE REVIEW

**Review by ShubhamTiwari55 — COMMENTED** [review]
@piyuuussh please add the screenshot of output as well

**Comment by piyuuussh** [comment]
add books page
notification

**Review by ShubhamTiwari55 — CHANGES_REQUESTED** [review]
@piyuuussh Like we discussed, also add the return date section in add book page so that we can keep a track of dues n all.

**Comment by piyuuussh** [comment]
final
The submission date and issue date both will be manually entered by the user

**Review by ShubhamTiwari55 — APPROVED** [review]
Splendid work @piyuuussh. Merging into main

**Pull request merged**
