### PR TITLE
SignUp UI updated

### PR DESCRIPTION
**Pull request by dev04sa**
@ShubhamTiwari55  @piyuuussh #26  isssue   is resolved .
Screenshot 2023-11-14 102955

### CODE REVIEW

**Review by piyuuussh — APPROVED** [review]
Great work @dev04sa.

**Comment by piyuuussh** [comment]
@ShubhamTiwari55 See if the issue you raised is resolve or anything else left

**Comment by ShubhamTiwari55** [comment]
@dev04sa can you plz make the white card to full width

**Comment by dev04sa** [comment]
> @dev04sa can you plz make the white card to full width

you can check card is already in its full width

**Comment by dev04sa** [comment]
now updated UI is here 
Screenshot 2023-11-14 174812

**Comment by ShubhamTiwari55** [comment]
@dev04sa That's looks good. Great work. Merging into main...

**Pull request merged**
